### ISSUE TITLE
Exam for student

### ISSUE THREAD

**Issue by akrindev** [smeducative/smeduverse-cbt#1]
Memungkinkan siswa untuk mengakses halaman CBT. setelah soal dan jadwal di buat kemudian pelaksanaan bagi siswa untuk mengakses halaman CBT khusus. dari sini siswa dapat masuk ke akun masing-masing kemudian melihat info data diri siswa. terdapat komponent untuk memasukkan kode ujian yang mana kode ini di gunakan untuk mengakses soal. 

Terdapat tampilan ujian yang terakhir di kerjakan oleh siswa, siswa dapat melihat ujian apa saja yang pernah dilaksanakan. 

### Task UI
- [x] tampilan login
- [x] dashboard
- [x] tampilan nama, kelas, nis, nisn, ttl, umur
- [x] komponent memasukkan kode ujian
- [x] tampilan informasi ujian
- [x] tampilan mengerjakan soal
- [x] tampilan sisa waktu ujian
- [x] tampilan pilihan jawaban
- [x] tampilan navigasi soal
- [x] tampilan hasil akhir ujian

## Task BE
- [x] siswa dapat login
- [x] siswa dapat logout
- [x] siswa dapat melihat informasi data diri
- [x] siswa dapat melihat jadwal ujian yang akan dilaksanakan
- [x] siswa dapat melihat informasi ujian
- [x] siswa dapat megerjakan soal
- [x] soal di tampilkan 1 per 1
- [x] navigasi untuk berpindah soal
- [x] menyimpan jawaban ke server secara real time
- [x] menyelesaikan soal dan menampilkan nilai akhir
